---
- name: Deploy Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Copy HTML template
      template:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Ensure NGINX is started
      service:
        name: nginx
        state: started
        enabled: yes
